# Generated by Django 5.2.10 on 2026-02-27 21:36
# Stock table is INSERT-ONLY; designed for PARTITION BY RANGE (created_at). DBA reference.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('entity_type', models.CharField(choices=[('PHARMACY', 'Pharmacy'), ('PUBLIC_FACILITY', 'Public facility')], db_index=True, max_length=16, verbose_name='entity type')),
                ('entity_id', models.UUIDField(db_index=True, help_text='UUID of pharmacy or public facility; FK resolved in application layer', verbose_name='entity ID')),
                ('movement_type', models.CharField(choices=[('IMPORT', 'Import'), ('B2B_IN', 'B2B in'), ('B2B_OUT', 'B2B out'), ('SALE', 'Sale'), ('RETURN', 'Return'), ('ADJUSTMENT', 'Adjustment'), ('RECALL_REMOVAL', 'Recall removal')], db_index=True, max_length=16, verbose_name='movement type')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('reference_id', models.UUIDField(blank=True, help_text='Source record: B2BOrder, InspectionFine, etc.', null=True, verbose_name='reference ID')),
                ('reference_type', models.CharField(blank=True, help_text='Model name of source record', max_length=100, verbose_name='reference type')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='medicines.nationallot', verbose_name='lot')),
            ],
            options={
                'verbose_name': 'stock movement',
                'verbose_name_plural': 'stock movements',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['entity_type', 'entity_id', 'lot'], name='stock_entity_lot_idx'), models.Index(fields=['lot', 'created_at'], name='stock_lot_created_idx'), models.Index(fields=['created_by', 'created_at'], name='stock_created_by_idx')],
            },
        ),
    ]
