# Generated by Django 5.2.10 on 2026-02-27 22:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('medicines', '0001_initial'),
        ('pharmacies', '0001_phase3_pharmacy_pharmacydocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='B2BOrder',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('APPROVED', 'Approved'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('CANCELLED', 'Cancelled'), ('REJECTED', 'Rejected')], db_index=True, default='DRAFT', max_length=12, verbose_name='status')),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='total amount (BIF)')),
                ('credit_used', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='credit used (BIF)')),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partial'), ('PAID', 'Paid')], db_index=True, default='PENDING', max_length=10, verbose_name='payment status')),
                ('price_override_approved', models.BooleanField(default=False, help_text='When True, unit prices may exceed medicine authorized price', verbose_name='price override approved')),
                ('buyer', models.ForeignKey(limit_choices_to={'pharmacy_type': 'RETAILER'}, on_delete=django.db.models.deletion.PROTECT, related_name='b2b_orders_bought', to='pharmacies.pharmacy', verbose_name='buyer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('seller', models.ForeignKey(limit_choices_to={'pharmacy_type': 'WHOLESALER'}, on_delete=django.db.models.deletion.PROTECT, related_name='b2b_orders_sold', to='pharmacies.pharmacy', verbose_name='seller')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'B2B order',
                'verbose_name_plural': 'B2B orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='B2BOrderItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_ordered', models.PositiveIntegerField(verbose_name='quantity ordered')),
                ('quantity_delivered', models.PositiveIntegerField(default=0, verbose_name='quantity delivered')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='unit price (BIF)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='b2b_order_items', to='medicines.nationallot', verbose_name='lot')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='b2b.b2border', verbose_name='order')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'B2B order item',
                'verbose_name_plural': 'B2B order items',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyCredit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('credit_limit', models.DecimalField(decimal_places=2, help_text='Maximum credit in BIF', max_digits=15, verbose_name='credit limit')),
                ('current_balance', models.DecimalField(decimal_places=2, default=0, help_text='Outstanding amount used (delivered orders not yet paid)', max_digits=15, verbose_name='current balance')),
                ('reserved_balance', models.DecimalField(decimal_places=2, default=0, help_text='Reserved for approved orders not yet delivered', max_digits=15, verbose_name='reserved balance')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('pharmacy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit', to='pharmacies.pharmacy', verbose_name='pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'pharmacy credit',
                'verbose_name_plural': 'pharmacy credits',
                'ordering': ['pharmacy__name'],
            },
        ),
        migrations.AddIndex(
            model_name='b2border',
            index=models.Index(fields=['seller', 'status'], name='b2b_b2borde_seller__87508a_idx'),
        ),
        migrations.AddIndex(
            model_name='b2border',
            index=models.Index(fields=['buyer', 'status'], name='b2b_b2borde_buyer_i_c6607c_idx'),
        ),
        migrations.AddIndex(
            model_name='b2border',
            index=models.Index(fields=['status', 'is_deleted'], name='b2b_b2borde_status_d0b4ac_idx'),
        ),
        migrations.AddIndex(
            model_name='b2borderitem',
            index=models.Index(fields=['order'], name='b2b_b2borde_order_i_37e544_idx'),
        ),
        migrations.AddIndex(
            model_name='b2borderitem',
            index=models.Index(fields=['lot'], name='b2b_b2borde_lot_id_6a5280_idx'),
        ),
        migrations.AddConstraint(
            model_name='b2borderitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_delivered__lte', models.F('quantity_ordered'))), name='b2b_item_delivered_lte_ordered'),
        ),
    ]
