# Generated by Django 5.2.10 on 2026-02-24 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('CREATE', 'Create'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('SOFT_DELETE', 'Soft Delete'), ('RESTORE', 'Restore'), ('STATUS_CHANGE', 'Status Change'), ('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('LOGIN_FAILED', 'Login Failed')], db_index=True, max_length=20, verbose_name='action')),
                ('model_name', models.CharField(db_index=True, max_length=100, verbose_name='model')),
                ('object_id', models.CharField(db_index=True, max_length=40, verbose_name='object ID')),
                ('old_values', models.JSONField(blank=True, null=True, verbose_name='old values')),
                ('new_values', models.JSONField(blank=True, null=True, verbose_name='new values')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('user_agent', models.TextField(blank=True, default='', verbose_name='user agent')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='timestamp')),
            ],
            options={
                'verbose_name': 'audit log',
                'verbose_name_plural': 'audit logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
