# Generated by Django 5.2.10 on 2026-02-27 21:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmacy',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Official or trading name of the pharmacy', max_length=255, verbose_name='name')),
                ('pharmacy_type', models.CharField(choices=[('WHOLESALER', 'Wholesaler'), ('RETAILER', 'Retailer')], db_index=True, max_length=12, verbose_name='type')),
                ('national_code', models.CharField(blank=True, db_index=True, help_text='Auto-generated format: PH-PROV-XXXX', max_length=20, unique=True, verbose_name='national code')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='longitude')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('SUSPENDED', 'Suspended'), ('ILLEGAL', 'Illegal')], db_index=True, default='PENDING', max_length=12, verbose_name='status')),
                ('qr_code', models.ImageField(blank=True, help_text='Generated on approval; stored in default storage (S3 in production)', null=True, upload_to='pharmacy_qr/%Y/%m/', verbose_name='QR code')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='address')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='phone')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('administrative_level', models.ForeignKey(help_text='Commune-level administrative level', limit_choices_to={'level_type': 'COMMUNE'}, on_delete=django.db.models.deletion.PROTECT, related_name='pharmacies', to='geography.administrativelevel', verbose_name='commune')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'pharmacy',
                'verbose_name_plural': 'pharmacies',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PharmacyDocument',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('LICENSE', 'License'), ('TAX_CLEARANCE', 'Tax clearance'), ('PHARMACIST_DIPLOMA', 'Pharmacist diploma'), ('OTHER', 'Other')], db_index=True, max_length=24, verbose_name='document type')),
                ('file', models.FileField(help_text='Uploaded file; stored in default storage (S3 in production)', upload_to='pharmacy_documents/%Y/%m/', verbose_name='file')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=10, verbose_name='status')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('rejection_reason', models.CharField(blank=True, max_length=500, verbose_name='rejection reason')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='pharmacies.pharmacy', verbose_name='pharmacy')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'pharmacy document',
                'verbose_name_plural': 'pharmacy documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['status', 'is_deleted'], name='pharmacies__status_91a007_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['pharmacy_type', 'status'], name='pharmacies__pharmac_2e8621_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacy',
            index=models.Index(fields=['administrative_level'], name='pharmacies__adminis_6ccfce_idx'),
        ),
        migrations.AddConstraint(
            model_name='pharmacy',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False), models.Q(('national_code', ''), _negated=True)), fields=('national_code',), name='unique_active_pharmacy_national_code'),
        ),
        migrations.AddIndex(
            model_name='pharmacydocument',
            index=models.Index(fields=['pharmacy', 'document_type'], name='pharmacies__pharmac_6fdcd6_idx'),
        ),
        migrations.AddIndex(
            model_name='pharmacydocument',
            index=models.Index(fields=['status'], name='pharmacies__status_405f69_idx'),
        ),
    ]
