"""
Core — Global Constants

Central registry of constants used across the platform.

@file core/constants.py
"""

AUDIT_ACTION_CREATE = 'CREATE'
AUDIT_ACTION_UPDATE = 'UPDATE'
AUDIT_ACTION_DELETE = 'DELETE'
AUDIT_ACTION_SOFT_DELETE = 'SOFT_DELETE'
AUDIT_ACTION_RESTORE = 'RESTORE'
AUDIT_ACTION_STATUS_CHANGE = 'STATUS_CHANGE'
AUDIT_ACTION_LOGIN = 'LOGIN'
AUDIT_ACTION_LOGOUT = 'LOGOUT'
AUDIT_ACTION_LOGIN_FAILED = 'LOGIN_FAILED'

SCOPE_PRIVATE = 'PRIVATE'
SCOPE_PUBLIC = 'PUBLIC'
SCOPE_NATIONAL = 'NATIONAL'

MAX_PAGE_SIZE = 200
DEFAULT_PAGE_SIZE = 25
