# Generated by Django 5.2.10 on 2026-02-24 21:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdministrativeLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='code')),
                ('level_type', models.CharField(choices=[('PROVINCE', 'Province'), ('COMMUNE', 'Commune'), ('ZONE', 'Zone'), ('COLLINE', 'Colline / Quartier')], db_index=True, max_length=10, verbose_name='level type')),
            ],
            options={
                'verbose_name': 'administrative level',
                'verbose_name_plural': 'administrative levels',
                'ordering': ['level_type', 'name'],
            },
        ),
    ]
