# Generated by Django 5.2.10 on 2026-02-24 21:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('geography', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='administrativelevel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='geography.administrativelevel', verbose_name='parent'),
        ),
        migrations.AddField(
            model_name='administrativelevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by'),
        ),
        migrations.AddIndex(
            model_name='administrativelevel',
            index=models.Index(fields=['level_type', 'parent'], name='geography_a_level_t_a1455a_idx'),
        ),
        migrations.AddIndex(
            model_name='administrativelevel',
            index=models.Index(fields=['name'], name='geography_a_name_2a0e70_idx'),
        ),
        migrations.AddConstraint(
            model_name='administrativelevel',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('level_type', 'PROVINCE'), ('parent__isnull', True)), models.Q(('level_type__in', ['COMMUNE', 'ZONE', 'COLLINE']), ('parent__isnull', False)), _connector='OR'), name='valid_parent_nullability'),
        ),
    ]
