# Generated by Django 5.2.10 on 2026-02-24 23:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NationalMedicine',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('atc_code', models.CharField(db_index=True, help_text='WHO ATC classification code (e.g. N02BE01)', max_length=7, verbose_name='ATC code')),
                ('inn', models.CharField(help_text='International Nonproprietary Name (e.g. Paracetamol)', max_length=255, verbose_name='INN')),
                ('brand_name', models.CharField(blank=True, max_length=255, verbose_name='brand name')),
                ('dosage_form', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('SYRUP', 'Syrup'), ('INJECTION', 'Injectable'), ('CREAM', 'Cream / Ointment'), ('DROPS', 'Drops'), ('INHALER', 'Inhaler'), ('SUPPOSITORY', 'Suppository'), ('POWDER', 'Powder'), ('SUSPENSION', 'Suspension'), ('SOLUTION', 'Solution'), ('OTHER', 'Other')], max_length=20, verbose_name='dosage form')),
                ('strength', models.CharField(help_text='e.g. 500mg, 250mg/5ml', max_length=100, verbose_name='strength')),
                ('packaging', models.CharField(blank=True, help_text='e.g. Box of 20 tablets, Bottle of 100ml', max_length=200, verbose_name='packaging')),
                ('manufacturer', models.CharField(blank=True, max_length=255, verbose_name='manufacturer')),
                ('country_of_origin', models.CharField(blank=True, max_length=100, verbose_name='country of origin')),
                ('authorized_price', models.DecimalField(decimal_places=2, help_text='Maximum regulated selling price in Burundian Francs', max_digits=15, verbose_name='authorized price (BIF)')),
                ('is_controlled', models.BooleanField(db_index=True, default=False, help_text='Narcotics, psychotropics, or other controlled substances', verbose_name='controlled substance')),
                ('status', models.CharField(choices=[('AUTHORIZED', 'Authorized'), ('BLOCKED', 'Blocked')], db_index=True, default='AUTHORIZED', max_length=12, verbose_name='status')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Flexible structured data for regulatory details', verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'national medicine',
                'verbose_name_plural': 'national medicines',
                'ordering': ['inn', 'strength'],
            },
        ),
        migrations.CreateModel(
            name='NationalLot',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='deleted at')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_number', models.CharField(help_text='Import batch / lot number', max_length=100, verbose_name='batch number')),
                ('manufacturing_date', models.DateField(verbose_name='manufacturing date')),
                ('expiry_date', models.DateField(db_index=True, verbose_name='expiry date')),
                ('quantity_imported', models.PositiveIntegerField(verbose_name='quantity imported')),
                ('import_reference', models.CharField(blank=True, help_text='Customs declaration or import permit number', max_length=100, verbose_name='import reference')),
                ('supplier', models.CharField(blank=True, max_length=255, verbose_name='supplier')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('BLOCKED', 'Blocked'), ('EXPIRED', 'Expired'), ('RECALLED', 'Recalled')], db_index=True, default='ACTIVE', max_length=10, verbose_name='status')),
                ('recall_reason', models.TextField(blank=True, help_text='Reason for recall, if applicable', verbose_name='recall reason')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='deleted by')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='medicines.nationalmedicine', verbose_name='medicine')),
            ],
            options={
                'verbose_name': 'national lot',
                'verbose_name_plural': 'national lots',
                'ordering': ['-expiry_date'],
            },
        ),
        migrations.AddIndex(
            model_name='nationalmedicine',
            index=models.Index(fields=['status', 'is_deleted'], name='medicines_n_status_4933a6_idx'),
        ),
        migrations.AddIndex(
            model_name='nationalmedicine',
            index=models.Index(fields=['atc_code'], name='medicines_n_atc_cod_019b66_idx'),
        ),
        migrations.AddIndex(
            model_name='nationalmedicine',
            index=models.Index(fields=['inn'], name='medicines_n_inn_c4ff34_idx'),
        ),
        migrations.AddIndex(
            model_name='nationalmedicine',
            index=models.Index(fields=['is_controlled', 'status'], name='medicines_n_is_cont_cdd536_idx'),
        ),
        migrations.AddConstraint(
            model_name='nationalmedicine',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('atc_code', 'dosage_form', 'strength', 'packaging', 'manufacturer'), name='unique_active_medicine_variant'),
        ),
        migrations.AddIndex(
            model_name='nationallot',
            index=models.Index(fields=['medicine', 'status'], name='medicines_n_medicin_79d120_idx'),
        ),
        migrations.AddIndex(
            model_name='nationallot',
            index=models.Index(fields=['status', 'expiry_date'], name='medicines_n_status_ecd3df_idx'),
        ),
        migrations.AddIndex(
            model_name='nationallot',
            index=models.Index(fields=['batch_number'], name='medicines_n_batch_n_379768_idx'),
        ),
        migrations.AddConstraint(
            model_name='nationallot',
            constraint=models.UniqueConstraint(condition=models.Q(('is_deleted', False)), fields=('medicine', 'batch_number'), name='unique_active_lot_batch'),
        ),
        migrations.AddConstraint(
            model_name='nationallot',
            constraint=models.CheckConstraint(condition=models.Q(('expiry_date__gt', models.F('manufacturing_date'))), name='lot_expiry_after_manufacturing'),
        ),
        migrations.AddConstraint(
            model_name='nationallot',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_imported__gt', 0)), name='lot_positive_quantity'),
        ),
    ]
